<?php 
	$ch = curl_init(); 
	curl_setopt($ch, CURLOPT_URL, "http://timkiemfb.com/cronjob-page-post-one/?limit=100"); 
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
	$output = curl_exec($ch); 
	curl_close($ch);
	$ch = curl_init(); 
	curl_setopt($ch, CURLOPT_URL, "http://timkiemfb.com/cronjob-page-post-one/?limit=100"); 
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
	$output = curl_exec($ch); 
	curl_close($ch);	
	$ch = curl_init(); 
	curl_setopt($ch, CURLOPT_URL, "http://timkiemfb.com/cronjob-page-post-one/?limit=100"); 
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
	$output = curl_exec($ch); 
	curl_close($ch);	
	$ch = curl_init(); 
	curl_setopt($ch, CURLOPT_URL, "http://timkiemfb.com/cronjob-page-post-one/?limit=100"); 
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
	$output = curl_exec($ch); 
	curl_close($ch);	
	$ch = curl_init(); 
	curl_setopt($ch, CURLOPT_URL, "http://timkiemfb.com/cronjob-page-post-one/?limit=100"); 
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
	$output = curl_exec($ch); 
	curl_close($ch);	
	$ch = curl_init(); 
	curl_setopt($ch, CURLOPT_URL, "http://timkiemfb.com/cronjob-page-post-one/?limit=100"); 
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
	$output = curl_exec($ch); 
	curl_close($ch);	
	$ch = curl_init(); 
	curl_setopt($ch, CURLOPT_URL, "http://timkiemfb.com/cronjob-page-post-one/?limit=100"); 
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
	$output = curl_exec($ch); 
	curl_close($ch);	
	$ch = curl_init(); 
	curl_setopt($ch, CURLOPT_URL, "http://timkiemfb.com/cronjob-page-post-one/?limit=100"); 
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
	$output = curl_exec($ch); 
	curl_close($ch);	
	$ch = curl_init(); 
	curl_setopt($ch, CURLOPT_URL, "http://timkiemfb.com/cronjob-page-post-one/?limit=100"); 
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
	$output = curl_exec($ch); 
	curl_close($ch);	
	$ch = curl_init(); 
	curl_setopt($ch, CURLOPT_URL, "http://timkiemfb.com/cronjob-page-post-one/?limit=100"); 
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
	$output = curl_exec($ch); 
	curl_close($ch);	
	die($output);
?>